version: '3.8'

services:
  back:
    build: ./back
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notagar-back.rule=Host(`notagar.diyor28.com`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.notagar-back.tls=true"
      - "traefik.http.routers.notagar-back.middlewares=notagar-back-stripprefix"
      - "traefik.http.middlewares.notagar-back-stripprefix.stripprefix.prefixes=/api"
    networks:
      - traefik

  front:
    build:
      context: ./front
      target: production
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notagar.rule=Host(`notagar.diyor28.com`) && Path(`/`)"
      - "traefik.http.routers.notagar.tls=true"
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
