version: '3.8'

services:
  back:
    container_name: notagar_back
    build: ./back
    restart: always
    networks:
      - traefik
    ports:
      - "3100:3100"

  front:
    container_name: notagar_front
    build: ./front
    restart: always
    networks:
      - traefik
    ports:
      - "3000:80"

networks:
  traefik:
    name: traefik
    external: true
