version: '3.8'

services:
  back:
    build: ./back
    restart: always
    networks:
      - traefik
    ports:
      - "3100:3100"

  front:
    build:
      context: ./front
      target: production
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notagar.rule=Host(`notagar.diyor28.com`)"
      - "traefik.http.routers.notagar.tls=true" # secure using TLS.
    networks:
      - traefik
    ports:
      - "80:80"

networks:
  traefik:
    name: traefik
    external: true
